FROM openjdk:17-jdk-slim
COPY build/libs/explorer-0.0.1-SNAPSHOT.jar ks-explorer-service-0.0.1-SNAPSHOT.jar
EXPOSE 4000
ENV ENV_NAME=prod
ENTRYPOINT ["java", "-jar", "ks-explorer-service-0.0.1-SNAPSHOT.jar"]