FROM gradle:7.6-jdk17 AS build
COPY src /home/app/src
COPY build.gradle /home/app
COPY settings.gradle /home/app
WORKDIR /home/app
RUN gradle build -x test --parallel

FROM openjdk:17-jdk-slim
COPY --from=build /home/app/build/libs/explorer-0.0.1-SNAPSHOT.jar /app/ks-explorer-service-0.0.1-SNAPSHOT.jar
EXPOSE 4000
ENV ENV_NAME=dev

ENTRYPOINT ["java", "-jar", "/app/ks-explorer-service-0.0.1-SNAPSHOT.jar"]