FROM gradle:7.1.1-jdk17 AS build
COPY src /home/app/src
COPY build.gradle /home/app
COPY settings.gradle /home/app
WORKDIR /home/app
RUN gradle clean build

FROM openjdk:17-jdk-slim
COPY build/libs/explorer-0.0.1-SNAPSHOT.jar ks-explorer-service-0.0.1-SNAPSHOT.jar
EXPOSE 4000
ENV ENV_NAME=dev

ENTRYPOINT ["java", "-jar", "ks-explorer-service-0.0.1-SNAPSHOT.jar"]